paths:
  static: ''
  uploads: uploads
timezone: Europe/Kyiv
markdown:
  engine: commonmark
  options: {}
collections_config:
  pages:
    path: ''
    icon: wysiwyg
  manus:
    path: __manus__
    icon: man
